var annotated =
[
    [ "dds", null, [
      [ "Agent", "classdds_1_1_agent.html", "classdds_1_1_agent" ],
      [ "AgentFactory", "classdds_1_1_agent_factory.html", "classdds_1_1_agent_factory" ],
      [ "BAMCPAgent", "classdds_1_1_b_a_m_c_p_agent.html", "classdds_1_1_b_a_m_c_p_agent" ],
      [ "CModel", "classdds_1_1_c_model.html", "classdds_1_1_c_model" ],
      [ "DirMultiDistribution", "classdds_1_1_dir_multi_distribution.html", "classdds_1_1_dir_multi_distribution" ],
      [ "EGreedyAgent", "classdds_1_1_e_greedy_agent.html", "classdds_1_1_e_greedy_agent" ],
      [ "EGreedyAgentFactory", "classdds_1_1_e_greedy_agent_factory.html", "classdds_1_1_e_greedy_agent_factory" ],
      [ "Experiment", "classdds_1_1_experiment.html", "classdds_1_1_experiment" ],
      [ "FormulaAgent", "classdds_1_1_formula_agent.html", "classdds_1_1_formula_agent" ],
      [ "FVariable", "classdds_1_1_f_variable.html", "classdds_1_1_f_variable" ],
      [ "MDP", "classdds_1_1_m_d_p.html", "classdds_1_1_m_d_p" ],
      [ "MDPDistribution", "classdds_1_1_m_d_p_distribution.html", "classdds_1_1_m_d_p_distribution" ],
      [ "Model", "classdds_1_1_model.html", "classdds_1_1_model" ],
      [ "OPPSCSAgent", "classdds_1_1_o_p_p_s_c_s_agent.html", "classdds_1_1_o_p_p_s_c_s_agent" ],
      [ "OPPSDSAgent", "classdds_1_1_o_p_p_s_d_s_agent.html", "classdds_1_1_o_p_p_s_d_s_agent" ],
      [ "OptimalAgent", "classdds_1_1_optimal_agent.html", "classdds_1_1_optimal_agent" ],
      [ "QMean", "classdds_1_1_q_mean.html", "classdds_1_1_q_mean" ],
      [ "QSelf", "classdds_1_1_q_self.html", "classdds_1_1_q_self" ],
      [ "QUniform", "classdds_1_1_q_uniform.html", "classdds_1_1_q_uniform" ],
      [ "QVar", "classdds_1_1_q_var.html", "classdds_1_1_q_var" ],
      [ "RandomAgent", "classdds_1_1_random_agent.html", "classdds_1_1_random_agent" ],
      [ "SoftMaxAgent", "classdds_1_1_soft_max_agent.html", "classdds_1_1_soft_max_agent" ],
      [ "SoftMaxAgentFactory", "classdds_1_1_soft_max_agent_factory.html", "classdds_1_1_soft_max_agent_factory" ],
      [ "VDBEEGreedyAgent", "classdds_1_1_v_d_b_e_e_greedy_agent.html", "classdds_1_1_v_d_b_e_e_greedy_agent" ],
      [ "VDBEEGreedyAgentFactory", "classdds_1_1_v_d_b_e_e_greedy_agent_factory.html", "classdds_1_1_v_d_b_e_e_greedy_agent_factory" ]
    ] ],
    [ "rl_utils", null, [
      [ "simulation", "namespacerl__utils_1_1simulation.html", "namespacerl__utils_1_1simulation" ]
    ] ],
    [ "utils", null, [
      [ "formula", "namespaceutils_1_1formula.html", "namespaceutils_1_1formula" ],
      [ "parsing", "namespaceutils_1_1parsing.html", "namespaceutils_1_1parsing" ],
      [ "Chrono", "classutils_1_1_chrono.html", "classutils_1_1_chrono" ],
      [ "RandomGen", "classutils_1_1_random_gen.html", null ],
      [ "Thread", "classutils_1_1_thread.html", "classutils_1_1_thread" ],
      [ "ThreadException", "classutils_1_1_thread_exception.html", "classutils_1_1_thread_exception" ],
      [ "UCB1", "classutils_1_1_u_c_b1.html", "classutils_1_1_u_c_b1" ],
      [ "UCT", "classutils_1_1_u_c_t.html", "classutils_1_1_u_c_t" ]
    ] ],
    [ "Agent", "class_agent.html", null ],
    [ "AgentData", "class_agent_data.html", "class_agent_data" ],
    [ "AgentException", "class_agent_exception.html", "class_agent_exception" ],
    [ "AgentFactory", "class_agent_factory.html", null ],
    [ "AgentFactoryException", "class_agent_factory_exception.html", "class_agent_factory_exception" ],
    [ "BAMCPAgent", "class_b_a_m_c_p_agent.html", null ],
    [ "Chrono", "class_chrono.html", null ],
    [ "CModel", "class_c_model.html", null ],
    [ "Constant", "class_constant.html", null ],
    [ "DirMultiDistribution", "class_dir_multi_distribution.html", null ],
    [ "EGreedyAgent", "class_e_greedy_agent.html", null ],
    [ "EGreedyAgentFactory", "class_e_greedy_agent_factory.html", null ],
    [ "Experiment", "class_experiment.html", null ],
    [ "ExperimentException", "class_experiment_exception.html", "class_experiment_exception" ],
    [ "Formula", "class_formula.html", null ],
    [ "FormulaAgent", "class_formula_agent.html", null ],
    [ "FormulaException", "class_formula_exception.html", null ],
    [ "FormulaVector", "class_formula_vector.html", "class_formula_vector" ],
    [ "FVariable", "class_f_variable.html", null ],
    [ "FVariableException", "class_f_variable_exception.html", "class_f_variable_exception" ],
    [ "IAgent", "class_i_agent.html", "class_i_agent" ],
    [ "IExperiment", "class_i_experiment.html", "class_i_experiment" ],
    [ "IMDP", "class_i_m_d_p.html", "class_i_m_d_p" ],
    [ "IMDPDistribution", "class_i_m_d_p_distribution.html", "class_i_m_d_p_distribution" ],
    [ "MDP", "class_m_d_p.html", null ],
    [ "MDPDistribution", "class_m_d_p_distribution.html", null ],
    [ "MDPDistributionException", "class_m_d_p_distribution_exception.html", "class_m_d_p_distribution_exception" ],
    [ "MDPException", "class_m_d_p_exception.html", "class_m_d_p_exception" ],
    [ "Model", "class_model.html", null ],
    [ "OPPSCSAgent", "class_o_p_p_s_c_s_agent.html", null ],
    [ "OPPSDSAgent", "class_o_p_p_s_d_s_agent.html", null ],
    [ "OptimalAgent", "class_optimal_agent.html", null ],
    [ "QMean", "class_q_mean.html", null ],
    [ "QSelf", "class_q_self.html", null ],
    [ "QUniform", "class_q_uniform.html", null ],
    [ "QVar", "class_q_var.html", null ],
    [ "RandomAgent", "class_random_agent.html", null ],
    [ "RandomGen", "class_random_gen.html", null ],
    [ "Serializable", "class_serializable.html", "class_serializable" ],
    [ "SerializableException", "class_serializable_exception.html", "class_serializable_exception" ],
    [ "SoftMaxAgent", "class_soft_max_agent.html", null ],
    [ "SoftMaxAgentFactory", "class_soft_max_agent_factory.html", null ],
    [ "Thread", "class_thread.html", null ],
    [ "ThreadException", "class_thread_exception.html", null ],
    [ "Token", "class_token.html", null ],
    [ "TokenException", "class_token_exception.html", null ],
    [ "UCB1", "class_u_c_b1.html", null ],
    [ "UCT", "class_u_c_t.html", null ],
    [ "Variable", "class_variable.html", null ],
    [ "VDBE", "class_v_d_b_e.html", null ],
    [ "VDBEEGreedyAgentFactory", "class_v_d_b_e_e_greedy_agent_factory.html", null ]
];